import { ConfigCatProvider } from '@/configcat';
import './global.css';

export const metadata = {
  title: 'Welcome to web',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const sdkKey = process.env.CONFIGCAT_SDK_KEY || '';
  return (
    <html lang="es">
      <body>
        <ConfigCatProvider sdkKey={sdkKey}>
          {children}
        </ConfigCatProvider>
      </body>
    </html>
  );
}
