import { ConfigCatProvider } from '@/configcat';
import { ObservabilityProvider, ErrorBoundary } from '@/observability';
import './global.css';

export const metadata = {
  title: 'Welcome to web',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const sdkKey = process.env.NEXT_PUBLIC_CONFIGCAT_SDK_KEY || '';

  return (
    <html lang="es">
      <body>
        <ObservabilityProvider>
          <ErrorBoundary>
            <ConfigCatProvider sdkKey={sdkKey}>
              {children}
            </ConfigCatProvider>
          </ErrorBoundary>
        </ObservabilityProvider>
      </body>
    </html>
  );
}